# This workflow is manually triggered and will produce the JS bundle source maps

name: Source Maps

on:
  workflow_dispatch:

jobs:
  build:

    environment: production

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: cp .env.example .env
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Android build
      run: yarn bundle:android
    - name: iOS build
      run: yarn bundle:ios
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
